### ISSUE TITLE
Return a object with 2 properties

### ISSUE THREAD

**Issue by dveraaas** [sasanchez7/calculatorv3#3]
https://github.com/sasanchez7/calculatorv3/blob/df713690590dc42e042c371f7e2a64b036171595/server/Server.cs#L39

**Comment by dbuenor** [comment]
You can use a Tuple if you dont want to create a new class...or as @dveraaas says...a new "ReturnClass" with two properties so you dont have to search trough an array for a value.

**Comment by sasanchez7** [comment]
In the end I decided to return objects from the models already created as it is easier for me, but tuplas is a good option to use in this case, better than returning array. Thanks for the recommendation  @dbuenor
