### ISSUE TITLE
Switch recomendations

### ISSUE THREAD

**Issue by dbuenor** [sasanchez7/calculatorv3#6]
In each case, u need to add "break;" at the end of case usually.

In this case is not needed because u do a return, but if u dont do a return, and execute the code...if you dont "break the case" it will continue executing the next case.

In addittion, when you have a switch, u always add a "default" case to catch all "but the cases" u have added to throw an exception to show the user that the case he selected doesnt exists like:

`
default:
     throw new NotImplementedException($"Selected Case is not avaible: {case}";
`
https://github.com/sasanchez7/calculatorv3/blob/df713690590dc42e042c371f7e2a64b036171595/server/Server.cs#L15

**Comment by sasanchez7** [comment]
I have been moving forward and this is not currently in my project. I separated the function in issue #2 in the commit sasanchez7@d0b059a13c056137848d2ddee061eae554890ebe . bc doing more than one thing in a function is bad practice. Thanks anyway for the suggestion @dbuenor .
