### ISSUE TITLE
NotImplemented Code

### ISSUE THREAD

**Issue by dbuenor** [sasanchez7/calculatorv3#7]
If you want to add some code or function to avoid compilation errors but its unfinished or you don't have ended yet, u always add the function like u have done, but inside the function u throw a NotImplementedException($"{nameof(function name)}");
to know that even if it compiled OK...the function is not implemented yet and it's not working.

https://github.com/sasanchez7/calculatorv3/blob/df713690590dc42e042c371f7e2a64b036171595/server/Server.cs#L49

**Comment by sasanchez7** [comment]
Fixed your issues number #7 in the commit sasanchez7@e35605a6dffff6df1c3a9d18f00eca932f2bcaf7
thank you for the suggestion @dbuenor
