### ISSUE TITLE
Do While

### ISSUE THREAD

**Issue by dbuenor** [sasanchez7/calculatorv3#8]
If you add a "do while" that is looping till you get the right answer, you need to show the user some kind of info to let him know that the proccess is looping because of the data he entered is wrong, so he can know why is wrong and how to solve it.

https://github.com/sasanchez7/calculatorv3/blob/df713690590dc42e042c371f7e2a64b036171595/client/Client.cs#L123

**Comment by sasanchez7** [comment]
You are right, i forgot to advise the usar what is happening. 
Fixed your issues number #8 in the commit sasanchez7@a44bca4f2e8c030328609488d9fef9cfb3eea9d5
thank you for the suggestion @dbuenor
