### ISSUE TITLE
Commented out code

### ISSUE THREAD

**Issue by dbuenor** [sasanchez7/calculatorv3#9]
If you change code from your app, dont comment out code....just remove. In a future, if you want to recover something you already have source code repository to check older versions.

And if u need to comment out code temporary, use compiler instruction "#if false".

That compiler instruction allows you to "invalidate" code so u make that its not compiled and not used in execution, but only modifies 2 lines (the line with the `#if false` and the line with `#endif`), because if you comment out all the lines, you re modifying *all* the lines and its preferrable to see 2 lines changed than a big chunk of code changed.

https://github.com/sasanchez7/calculatorv3/blob/df713690590dc42e042c371f7e2a64b036171595/client/Program.cs#L93

**Comment by sasanchez7** [comment]
Fixed your issues number #9 in the commit sasanchez7@fa3b2154905019e354fe58548d5b8c45f9d2c5fc
thank you for the suggestion @dbuenor
